# version: 0.2

# phases:
#   pre_build:
#     commands:
#       - echo Installing source NPM dependencies.......
#       - cd frontend
#       - npm install -f 
#   build:
#     commands:
#       - echo Build started on 'date'
#       - npm run plugin
#   post_build:
#     commands:
#       # copy the contents of /build to S3
#        - aws s3 rm s3://$BUCKET_NAME --recursive
#        - aws s3 cp --recursive ./dist/ s3://$BUCKET_NAME/
#        - aws cloudfront create-invalidation --distribution-id $DIST_ID --paths '/*'
# artifacts:
#   files:
#     - '**/*'
#   base-directory: frontend/dist...
